// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UraniaWeb.Models;

namespace UraniaWeb.Migrations
{
    [DbContext(typeof(UraniaWebDbContext))]
    [Migration("20220420012703_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UraniaWeb.Models.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameAdmin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PassAdmin")
                        .HasColumnType("int");

                    b.HasKey("IdAdmin");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("UraniaWeb.Models.Article", b =>
                {
                    b.Property<int>("IdAticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescritionArticle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleArticle")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UrlImagen1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSound1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAticle");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("UraniaWeb.Models.Slider", b =>
                {
                    b.Property<int>("IdSlider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TitleSlider")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UrlSlider1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSlider");

                    b.ToTable("Slider");
                });
#pragma warning restore 612, 618
        }
    }
}
